// Variables that describe what you want to do

export const SET_USER_AUTHENTICATED = 'SET_USER_AUTHENTICATED';
export const IS_LOCATION_PERMISSION_GRANTED = 'IS_LOCATION_PERMISSION_GRANTED';
export const SET_USER_LOCATION = 'SET_USER_LOCATION';
export const SET_ROUTE_DISTANCE_METERS = 'SET_ROUTE_DISTANCE_METERS';
export const SET_RANDOM_POLYGON_COORDINATES = 'SET_RANDOM_POLYGON_COORDINATES';
export const SET_FINAL_ROUTE_LINESTRING = 'SET_FINAL_ROUTE_LINESTRING';
export const SET_CALCULATED_ROUTE_DISTANCE_METERS = 'SET_CALCULATED_ROUTE_DISTANCE_METERS;';
export const SET_MOST_NORTH_EASTERN_COORDINATES = 'SET_MOST_NORTH_EASTERN_COORDINATES';
export const SET_MOST_SOUTH_WESTERN_COORDINATES = 'SET_MOST_SOUTH_WESTERN_COORDINATES';
export const SET_IS_ROUTE_CARDS_SHOWN = 'SET_IS_ROUTE_CARDS_SHOWN';
export const SET_SAVED_ROUTES_RESPONSE = 'SET_SAVED_ROUTES_RESPONSE';
export const SET_MAP_IMAGE_URI = 'SET_MAP_IMAGE_URI';
export const SET_USER_ACCOUNT_DETAILS = 'SET_USER_ACCOUNT_DETAILS';